// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ng_message.proto

//package Netgo.Library;

package server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_JoinLobby              MessageType = 0
	MessageType_LeaveLobby             MessageType = 1
	MessageType_CreateRoom             MessageType = 2
	MessageType_JoinRoom               MessageType = 3
	MessageType_JoinOrCreateRoom       MessageType = 4
	MessageType_LeaveRoom              MessageType = 5
	MessageType_RPC                    MessageType = 6
	MessageType_Instantiation          MessageType = 7
	MessageType_ViewSync               MessageType = 8
	MessageType_CustomEvent            MessageType = 9
	MessageType_SubscribeMsgChannels   MessageType = 10
	MessageType_UnSubscribeMsgChannels MessageType = 11
)

var MessageType_name = map[int32]string{
	0:  "JoinLobby",
	1:  "LeaveLobby",
	2:  "CreateRoom",
	3:  "JoinRoom",
	4:  "JoinOrCreateRoom",
	5:  "LeaveRoom",
	6:  "RPC",
	7:  "Instantiation",
	8:  "ViewSync",
	9:  "CustomEvent",
	10: "SubscribeMsgChannels",
	11: "UnSubscribeMsgChannels",
}

var MessageType_value = map[string]int32{
	"JoinLobby":              0,
	"LeaveLobby":             1,
	"CreateRoom":             2,
	"JoinRoom":               3,
	"JoinOrCreateRoom":       4,
	"LeaveRoom":              5,
	"RPC":                    6,
	"Instantiation":          7,
	"ViewSync":               8,
	"CustomEvent":            9,
	"SubscribeMsgChannels":   10,
	"UnSubscribeMsgChannels": 11,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{0}
}

type CacheOptions int32

const (
	CacheOptions_AddToRoomCache      CacheOptions = 0
	CacheOptions_RemoveFromRoomCache CacheOptions = 1
)

var CacheOptions_name = map[int32]string{
	0: "AddToRoomCache",
	1: "RemoveFromRoomCache",
}

var CacheOptions_value = map[string]int32{
	"AddToRoomCache":      0,
	"RemoveFromRoomCache": 1,
}

func (x CacheOptions) String() string {
	return proto.EnumName(CacheOptions_name, int32(x))
}

func (CacheOptions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{1}
}

//event relvelant structs
type RPCTarget int32

const (
	RPCTarget_All    RPCTarget = 0
	RPCTarget_Others RPCTarget = 1
)

var RPCTarget_name = map[int32]string{
	0: "All",
	1: "Others",
}

var RPCTarget_value = map[string]int32{
	"All":    0,
	"Others": 1,
}

func (x RPCTarget) String() string {
	return proto.EnumName(RPCTarget_name, int32(x))
}

func (RPCTarget) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{2}
}

type SocketStatus int32

const (
	SocketStatus_Disconnected SocketStatus = 0
	SocketStatus_Connected    SocketStatus = 1
)

var SocketStatus_name = map[int32]string{
	0: "Disconnected",
	1: "Connected",
}

var SocketStatus_value = map[string]int32{
	"Disconnected": 0,
	"Connected":    1,
}

func (x SocketStatus) String() string {
	return proto.EnumName(SocketStatus_name, int32(x))
}

func (SocketStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{3}
}

type ReceiveMessageType int32

const (
	ReceiveMessageType_ResponseSocketStatus ReceiveMessageType = 0
	ReceiveMessageType_ResponseOperation    ReceiveMessageType = 1
	ReceiveMessageType_Forward              ReceiveMessageType = 2
)

var ReceiveMessageType_name = map[int32]string{
	0: "ResponseSocketStatus",
	1: "ResponseOperation",
	2: "Forward",
}

var ReceiveMessageType_value = map[string]int32{
	"ResponseSocketStatus": 0,
	"ResponseOperation":    1,
	"Forward":              2,
}

func (x ReceiveMessageType) String() string {
	return proto.EnumName(ReceiveMessageType_name, int32(x))
}

func (ReceiveMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{4}
}

//the NGAny is a union,only one type is set
type NGAny struct {
	// Types that are valid to be assigned to NgType:
	//	*NGAny_NgDouble
	//	*NGAny_NgFloat
	//	*NGAny_NgInt32
	//	*NGAny_NgInt64
	//	*NGAny_NgUint32
	//	*NGAny_NgUint64
	//	*NGAny_NgSint32
	//	*NGAny_NgSint64
	//	*NGAny_NgFixed32
	//	*NGAny_NgFixed64
	//	*NGAny_NgSfixed32
	//	*NGAny_NgSfixed64
	//	*NGAny_NgBool
	//	*NGAny_NgString
	//	*NGAny_NgBytes
	//	*NGAny_NgVector3
	//	*NGAny_NgQuaternion
	//	*NGAny_NgColor
	NgType               isNGAny_NgType `protobuf_oneof:"ngType"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NGAny) Reset()         { *m = NGAny{} }
func (m *NGAny) String() string { return proto.CompactTextString(m) }
func (*NGAny) ProtoMessage()    {}
func (*NGAny) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{0}
}

func (m *NGAny) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NGAny.Unmarshal(m, b)
}
func (m *NGAny) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NGAny.Marshal(b, m, deterministic)
}
func (m *NGAny) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NGAny.Merge(m, src)
}
func (m *NGAny) XXX_Size() int {
	return xxx_messageInfo_NGAny.Size(m)
}
func (m *NGAny) XXX_DiscardUnknown() {
	xxx_messageInfo_NGAny.DiscardUnknown(m)
}

var xxx_messageInfo_NGAny proto.InternalMessageInfo

type isNGAny_NgType interface {
	isNGAny_NgType()
}

type NGAny_NgDouble struct {
	NgDouble float64 `protobuf:"fixed64,11,opt,name=ngDouble,proto3,oneof"`
}

type NGAny_NgFloat struct {
	NgFloat float32 `protobuf:"fixed32,12,opt,name=ngFloat,proto3,oneof"`
}

type NGAny_NgInt32 struct {
	NgInt32 int32 `protobuf:"varint,13,opt,name=ngInt32,proto3,oneof"`
}

type NGAny_NgInt64 struct {
	NgInt64 int64 `protobuf:"varint,14,opt,name=ngInt64,proto3,oneof"`
}

type NGAny_NgUint32 struct {
	NgUint32 uint32 `protobuf:"varint,15,opt,name=ngUint32,proto3,oneof"`
}

type NGAny_NgUint64 struct {
	NgUint64 uint64 `protobuf:"varint,16,opt,name=ngUint64,proto3,oneof"`
}

type NGAny_NgSint32 struct {
	NgSint32 int32 `protobuf:"zigzag32,17,opt,name=ngSint32,proto3,oneof"`
}

type NGAny_NgSint64 struct {
	NgSint64 int64 `protobuf:"zigzag64,18,opt,name=ngSint64,proto3,oneof"`
}

type NGAny_NgFixed32 struct {
	NgFixed32 uint32 `protobuf:"fixed32,19,opt,name=ngFixed32,proto3,oneof"`
}

type NGAny_NgFixed64 struct {
	NgFixed64 uint64 `protobuf:"fixed64,20,opt,name=ngFixed64,proto3,oneof"`
}

type NGAny_NgSfixed32 struct {
	NgSfixed32 int32 `protobuf:"fixed32,21,opt,name=ngSfixed32,proto3,oneof"`
}

type NGAny_NgSfixed64 struct {
	NgSfixed64 int64 `protobuf:"fixed64,22,opt,name=ngSfixed64,proto3,oneof"`
}

type NGAny_NgBool struct {
	NgBool bool `protobuf:"varint,23,opt,name=ngBool,proto3,oneof"`
}

type NGAny_NgString struct {
	NgString string `protobuf:"bytes,24,opt,name=ngString,proto3,oneof"`
}

type NGAny_NgBytes struct {
	NgBytes []byte `protobuf:"bytes,25,opt,name=ngBytes,proto3,oneof"`
}

type NGAny_NgVector3 struct {
	NgVector3 *NGVector3 `protobuf:"bytes,31,opt,name=ngVector3,proto3,oneof"`
}

type NGAny_NgQuaternion struct {
	NgQuaternion *NGQuaternion `protobuf:"bytes,32,opt,name=ngQuaternion,proto3,oneof"`
}

type NGAny_NgColor struct {
	NgColor *NGColor `protobuf:"bytes,33,opt,name=ngColor,proto3,oneof"`
}

func (*NGAny_NgDouble) isNGAny_NgType() {}

func (*NGAny_NgFloat) isNGAny_NgType() {}

func (*NGAny_NgInt32) isNGAny_NgType() {}

func (*NGAny_NgInt64) isNGAny_NgType() {}

func (*NGAny_NgUint32) isNGAny_NgType() {}

func (*NGAny_NgUint64) isNGAny_NgType() {}

func (*NGAny_NgSint32) isNGAny_NgType() {}

func (*NGAny_NgSint64) isNGAny_NgType() {}

func (*NGAny_NgFixed32) isNGAny_NgType() {}

func (*NGAny_NgFixed64) isNGAny_NgType() {}

func (*NGAny_NgSfixed32) isNGAny_NgType() {}

func (*NGAny_NgSfixed64) isNGAny_NgType() {}

func (*NGAny_NgBool) isNGAny_NgType() {}

func (*NGAny_NgString) isNGAny_NgType() {}

func (*NGAny_NgBytes) isNGAny_NgType() {}

func (*NGAny_NgVector3) isNGAny_NgType() {}

func (*NGAny_NgQuaternion) isNGAny_NgType() {}

func (*NGAny_NgColor) isNGAny_NgType() {}

func (m *NGAny) GetNgType() isNGAny_NgType {
	if m != nil {
		return m.NgType
	}
	return nil
}

func (m *NGAny) GetNgDouble() float64 {
	if x, ok := m.GetNgType().(*NGAny_NgDouble); ok {
		return x.NgDouble
	}
	return 0
}

func (m *NGAny) GetNgFloat() float32 {
	if x, ok := m.GetNgType().(*NGAny_NgFloat); ok {
		return x.NgFloat
	}
	return 0
}

func (m *NGAny) GetNgInt32() int32 {
	if x, ok := m.GetNgType().(*NGAny_NgInt32); ok {
		return x.NgInt32
	}
	return 0
}

func (m *NGAny) GetNgInt64() int64 {
	if x, ok := m.GetNgType().(*NGAny_NgInt64); ok {
		return x.NgInt64
	}
	return 0
}

func (m *NGAny) GetNgUint32() uint32 {
	if x, ok := m.GetNgType().(*NGAny_NgUint32); ok {
		return x.NgUint32
	}
	return 0
}

func (m *NGAny) GetNgUint64() uint64 {
	if x, ok := m.GetNgType().(*NGAny_NgUint64); ok {
		return x.NgUint64
	}
	return 0
}

func (m *NGAny) GetNgSint32() int32 {
	if x, ok := m.GetNgType().(*NGAny_NgSint32); ok {
		return x.NgSint32
	}
	return 0
}

func (m *NGAny) GetNgSint64() int64 {
	if x, ok := m.GetNgType().(*NGAny_NgSint64); ok {
		return x.NgSint64
	}
	return 0
}

func (m *NGAny) GetNgFixed32() uint32 {
	if x, ok := m.GetNgType().(*NGAny_NgFixed32); ok {
		return x.NgFixed32
	}
	return 0
}

func (m *NGAny) GetNgFixed64() uint64 {
	if x, ok := m.GetNgType().(*NGAny_NgFixed64); ok {
		return x.NgFixed64
	}
	return 0
}

func (m *NGAny) GetNgSfixed32() int32 {
	if x, ok := m.GetNgType().(*NGAny_NgSfixed32); ok {
		return x.NgSfixed32
	}
	return 0
}

func (m *NGAny) GetNgSfixed64() int64 {
	if x, ok := m.GetNgType().(*NGAny_NgSfixed64); ok {
		return x.NgSfixed64
	}
	return 0
}

func (m *NGAny) GetNgBool() bool {
	if x, ok := m.GetNgType().(*NGAny_NgBool); ok {
		return x.NgBool
	}
	return false
}

func (m *NGAny) GetNgString() string {
	if x, ok := m.GetNgType().(*NGAny_NgString); ok {
		return x.NgString
	}
	return ""
}

func (m *NGAny) GetNgBytes() []byte {
	if x, ok := m.GetNgType().(*NGAny_NgBytes); ok {
		return x.NgBytes
	}
	return nil
}

func (m *NGAny) GetNgVector3() *NGVector3 {
	if x, ok := m.GetNgType().(*NGAny_NgVector3); ok {
		return x.NgVector3
	}
	return nil
}

func (m *NGAny) GetNgQuaternion() *NGQuaternion {
	if x, ok := m.GetNgType().(*NGAny_NgQuaternion); ok {
		return x.NgQuaternion
	}
	return nil
}

func (m *NGAny) GetNgColor() *NGColor {
	if x, ok := m.GetNgType().(*NGAny_NgColor); ok {
		return x.NgColor
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NGAny) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NGAny_NgDouble)(nil),
		(*NGAny_NgFloat)(nil),
		(*NGAny_NgInt32)(nil),
		(*NGAny_NgInt64)(nil),
		(*NGAny_NgUint32)(nil),
		(*NGAny_NgUint64)(nil),
		(*NGAny_NgSint32)(nil),
		(*NGAny_NgSint64)(nil),
		(*NGAny_NgFixed32)(nil),
		(*NGAny_NgFixed64)(nil),
		(*NGAny_NgSfixed32)(nil),
		(*NGAny_NgSfixed64)(nil),
		(*NGAny_NgBool)(nil),
		(*NGAny_NgString)(nil),
		(*NGAny_NgBytes)(nil),
		(*NGAny_NgVector3)(nil),
		(*NGAny_NgQuaternion)(nil),
		(*NGAny_NgColor)(nil),
	}
}

type CommonOptions struct {
	SendToChannelIds     []uint32     `protobuf:"varint,1,rep,packed,name=sendToChannelIds,proto3" json:"sendToChannelIds,omitempty"`
	CacheOptions         CacheOptions `protobuf:"varint,2,opt,name=cacheOptions,proto3,enum=server.CacheOptions" json:"cacheOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CommonOptions) Reset()         { *m = CommonOptions{} }
func (m *CommonOptions) String() string { return proto.CompactTextString(m) }
func (*CommonOptions) ProtoMessage()    {}
func (*CommonOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{1}
}

func (m *CommonOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonOptions.Unmarshal(m, b)
}
func (m *CommonOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonOptions.Marshal(b, m, deterministic)
}
func (m *CommonOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonOptions.Merge(m, src)
}
func (m *CommonOptions) XXX_Size() int {
	return xxx_messageInfo_CommonOptions.Size(m)
}
func (m *CommonOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonOptions.DiscardUnknown(m)
}

var xxx_messageInfo_CommonOptions proto.InternalMessageInfo

func (m *CommonOptions) GetSendToChannelIds() []uint32 {
	if m != nil {
		return m.SendToChannelIds
	}
	return nil
}

func (m *CommonOptions) GetCacheOptions() CacheOptions {
	if m != nil {
		return m.CacheOptions
	}
	return CacheOptions_AddToRoomCache
}

type CreateRoomParams struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MaxNumber            uint32   `protobuf:"varint,2,opt,name=maxNumber,proto3" json:"maxNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomParams) Reset()         { *m = CreateRoomParams{} }
func (m *CreateRoomParams) String() string { return proto.CompactTextString(m) }
func (*CreateRoomParams) ProtoMessage()    {}
func (*CreateRoomParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{2}
}

func (m *CreateRoomParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomParams.Unmarshal(m, b)
}
func (m *CreateRoomParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomParams.Marshal(b, m, deterministic)
}
func (m *CreateRoomParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomParams.Merge(m, src)
}
func (m *CreateRoomParams) XXX_Size() int {
	return xxx_messageInfo_CreateRoomParams.Size(m)
}
func (m *CreateRoomParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomParams proto.InternalMessageInfo

func (m *CreateRoomParams) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *CreateRoomParams) GetMaxNumber() uint32 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type CreateRoomResponseParams struct {
	ReturnValue          uint32   `protobuf:"varint,1,opt,name=returnValue,proto3" json:"returnValue,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PeerId               uint32   `protobuf:"varint,3,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomResponseParams) Reset()         { *m = CreateRoomResponseParams{} }
func (m *CreateRoomResponseParams) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponseParams) ProtoMessage()    {}
func (*CreateRoomResponseParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{3}
}

func (m *CreateRoomResponseParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponseParams.Unmarshal(m, b)
}
func (m *CreateRoomResponseParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponseParams.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponseParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponseParams.Merge(m, src)
}
func (m *CreateRoomResponseParams) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponseParams.Size(m)
}
func (m *CreateRoomResponseParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponseParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponseParams proto.InternalMessageInfo

func (m *CreateRoomResponseParams) GetReturnValue() uint32 {
	if m != nil {
		return m.ReturnValue
	}
	return 0
}

func (m *CreateRoomResponseParams) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateRoomResponseParams) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

type JoinRoomParams struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomParams) Reset()         { *m = JoinRoomParams{} }
func (m *JoinRoomParams) String() string { return proto.CompactTextString(m) }
func (*JoinRoomParams) ProtoMessage()    {}
func (*JoinRoomParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{4}
}

func (m *JoinRoomParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomParams.Unmarshal(m, b)
}
func (m *JoinRoomParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomParams.Marshal(b, m, deterministic)
}
func (m *JoinRoomParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomParams.Merge(m, src)
}
func (m *JoinRoomParams) XXX_Size() int {
	return xxx_messageInfo_JoinRoomParams.Size(m)
}
func (m *JoinRoomParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomParams.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomParams proto.InternalMessageInfo

func (m *JoinRoomParams) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type JoinRoomResponseParams struct {
	ReturnValue          uint32   `protobuf:"varint,1,opt,name=returnValue,proto3" json:"returnValue,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PeerId               uint32   `protobuf:"varint,3,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomResponseParams) Reset()         { *m = JoinRoomResponseParams{} }
func (m *JoinRoomResponseParams) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponseParams) ProtoMessage()    {}
func (*JoinRoomResponseParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{5}
}

func (m *JoinRoomResponseParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponseParams.Unmarshal(m, b)
}
func (m *JoinRoomResponseParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponseParams.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponseParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponseParams.Merge(m, src)
}
func (m *JoinRoomResponseParams) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponseParams.Size(m)
}
func (m *JoinRoomResponseParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponseParams.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponseParams proto.InternalMessageInfo

func (m *JoinRoomResponseParams) GetReturnValue() uint32 {
	if m != nil {
		return m.ReturnValue
	}
	return 0
}

func (m *JoinRoomResponseParams) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JoinRoomResponseParams) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

type JoinRoomForwardParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoomForwardParams) Reset()         { *m = JoinRoomForwardParams{} }
func (m *JoinRoomForwardParams) String() string { return proto.CompactTextString(m) }
func (*JoinRoomForwardParams) ProtoMessage()    {}
func (*JoinRoomForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{6}
}

func (m *JoinRoomForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomForwardParams.Unmarshal(m, b)
}
func (m *JoinRoomForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomForwardParams.Marshal(b, m, deterministic)
}
func (m *JoinRoomForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomForwardParams.Merge(m, src)
}
func (m *JoinRoomForwardParams) XXX_Size() int {
	return xxx_messageInfo_JoinRoomForwardParams.Size(m)
}
func (m *JoinRoomForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomForwardParams proto.InternalMessageInfo

type JoinOrCreateRoomParams struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	MaxNumber            uint32   `protobuf:"varint,2,opt,name=maxNumber,proto3" json:"maxNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinOrCreateRoomParams) Reset()         { *m = JoinOrCreateRoomParams{} }
func (m *JoinOrCreateRoomParams) String() string { return proto.CompactTextString(m) }
func (*JoinOrCreateRoomParams) ProtoMessage()    {}
func (*JoinOrCreateRoomParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{7}
}

func (m *JoinOrCreateRoomParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOrCreateRoomParams.Unmarshal(m, b)
}
func (m *JoinOrCreateRoomParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOrCreateRoomParams.Marshal(b, m, deterministic)
}
func (m *JoinOrCreateRoomParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOrCreateRoomParams.Merge(m, src)
}
func (m *JoinOrCreateRoomParams) XXX_Size() int {
	return xxx_messageInfo_JoinOrCreateRoomParams.Size(m)
}
func (m *JoinOrCreateRoomParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOrCreateRoomParams.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOrCreateRoomParams proto.InternalMessageInfo

func (m *JoinOrCreateRoomParams) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *JoinOrCreateRoomParams) GetMaxNumber() uint32 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type JoinOrCreateRoomResponseParams struct {
	ReturnValue          uint32   `protobuf:"varint,1,opt,name=returnValue,proto3" json:"returnValue,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PeerId               uint32   `protobuf:"varint,3,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinOrCreateRoomResponseParams) Reset()         { *m = JoinOrCreateRoomResponseParams{} }
func (m *JoinOrCreateRoomResponseParams) String() string { return proto.CompactTextString(m) }
func (*JoinOrCreateRoomResponseParams) ProtoMessage()    {}
func (*JoinOrCreateRoomResponseParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{8}
}

func (m *JoinOrCreateRoomResponseParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOrCreateRoomResponseParams.Unmarshal(m, b)
}
func (m *JoinOrCreateRoomResponseParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOrCreateRoomResponseParams.Marshal(b, m, deterministic)
}
func (m *JoinOrCreateRoomResponseParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOrCreateRoomResponseParams.Merge(m, src)
}
func (m *JoinOrCreateRoomResponseParams) XXX_Size() int {
	return xxx_messageInfo_JoinOrCreateRoomResponseParams.Size(m)
}
func (m *JoinOrCreateRoomResponseParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOrCreateRoomResponseParams.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOrCreateRoomResponseParams proto.InternalMessageInfo

func (m *JoinOrCreateRoomResponseParams) GetReturnValue() uint32 {
	if m != nil {
		return m.ReturnValue
	}
	return 0
}

func (m *JoinOrCreateRoomResponseParams) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JoinOrCreateRoomResponseParams) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

type JoinOrCreateRoomForwardParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinOrCreateRoomForwardParams) Reset()         { *m = JoinOrCreateRoomForwardParams{} }
func (m *JoinOrCreateRoomForwardParams) String() string { return proto.CompactTextString(m) }
func (*JoinOrCreateRoomForwardParams) ProtoMessage()    {}
func (*JoinOrCreateRoomForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{9}
}

func (m *JoinOrCreateRoomForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinOrCreateRoomForwardParams.Unmarshal(m, b)
}
func (m *JoinOrCreateRoomForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinOrCreateRoomForwardParams.Marshal(b, m, deterministic)
}
func (m *JoinOrCreateRoomForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinOrCreateRoomForwardParams.Merge(m, src)
}
func (m *JoinOrCreateRoomForwardParams) XXX_Size() int {
	return xxx_messageInfo_JoinOrCreateRoomForwardParams.Size(m)
}
func (m *JoinOrCreateRoomForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinOrCreateRoomForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_JoinOrCreateRoomForwardParams proto.InternalMessageInfo

type LeaveRoomParams struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomParams) Reset()         { *m = LeaveRoomParams{} }
func (m *LeaveRoomParams) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomParams) ProtoMessage()    {}
func (*LeaveRoomParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{10}
}

func (m *LeaveRoomParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomParams.Unmarshal(m, b)
}
func (m *LeaveRoomParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomParams.Marshal(b, m, deterministic)
}
func (m *LeaveRoomParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomParams.Merge(m, src)
}
func (m *LeaveRoomParams) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomParams.Size(m)
}
func (m *LeaveRoomParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomParams.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomParams proto.InternalMessageInfo

func (m *LeaveRoomParams) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type LeaveRoomResponseParams struct {
	ReturnValue          uint32   `protobuf:"varint,1,opt,name=returnValue,proto3" json:"returnValue,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PeerId               uint32   `protobuf:"varint,3,opt,name=peerId,proto3" json:"peerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomResponseParams) Reset()         { *m = LeaveRoomResponseParams{} }
func (m *LeaveRoomResponseParams) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomResponseParams) ProtoMessage()    {}
func (*LeaveRoomResponseParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{11}
}

func (m *LeaveRoomResponseParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomResponseParams.Unmarshal(m, b)
}
func (m *LeaveRoomResponseParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomResponseParams.Marshal(b, m, deterministic)
}
func (m *LeaveRoomResponseParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomResponseParams.Merge(m, src)
}
func (m *LeaveRoomResponseParams) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomResponseParams.Size(m)
}
func (m *LeaveRoomResponseParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomResponseParams.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomResponseParams proto.InternalMessageInfo

func (m *LeaveRoomResponseParams) GetReturnValue() uint32 {
	if m != nil {
		return m.ReturnValue
	}
	return 0
}

func (m *LeaveRoomResponseParams) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LeaveRoomResponseParams) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

type LeaveRoomForwardParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomForwardParams) Reset()         { *m = LeaveRoomForwardParams{} }
func (m *LeaveRoomForwardParams) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomForwardParams) ProtoMessage()    {}
func (*LeaveRoomForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{12}
}

func (m *LeaveRoomForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomForwardParams.Unmarshal(m, b)
}
func (m *LeaveRoomForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomForwardParams.Marshal(b, m, deterministic)
}
func (m *LeaveRoomForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomForwardParams.Merge(m, src)
}
func (m *LeaveRoomForwardParams) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomForwardParams.Size(m)
}
func (m *LeaveRoomForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomForwardParams proto.InternalMessageInfo

//RPC parameters send from client to server
type RPCParams struct {
	Options              *CommonOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Target               RPCTarget      `protobuf:"varint,2,opt,name=target,proto3,enum=server.RPCTarget" json:"target,omitempty"`
	ViewID               uint32         `protobuf:"varint,3,opt,name=viewID,proto3" json:"viewID,omitempty"`
	MethodName           string         `protobuf:"bytes,4,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Parameters           []*NGAny       `protobuf:"bytes,5,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RPCParams) Reset()         { *m = RPCParams{} }
func (m *RPCParams) String() string { return proto.CompactTextString(m) }
func (*RPCParams) ProtoMessage()    {}
func (*RPCParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{13}
}

func (m *RPCParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCParams.Unmarshal(m, b)
}
func (m *RPCParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCParams.Marshal(b, m, deterministic)
}
func (m *RPCParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCParams.Merge(m, src)
}
func (m *RPCParams) XXX_Size() int {
	return xxx_messageInfo_RPCParams.Size(m)
}
func (m *RPCParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCParams.DiscardUnknown(m)
}

var xxx_messageInfo_RPCParams proto.InternalMessageInfo

func (m *RPCParams) GetOptions() *CommonOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *RPCParams) GetTarget() RPCTarget {
	if m != nil {
		return m.Target
	}
	return RPCTarget_All
}

func (m *RPCParams) GetViewID() uint32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *RPCParams) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *RPCParams) GetParameters() []*NGAny {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type RPCForwardParams struct {
	ViewID               uint32   `protobuf:"varint,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	MethodName           string   `protobuf:"bytes,2,opt,name=methodName,proto3" json:"methodName,omitempty"`
	Parameters           []*NGAny `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCForwardParams) Reset()         { *m = RPCForwardParams{} }
func (m *RPCForwardParams) String() string { return proto.CompactTextString(m) }
func (*RPCForwardParams) ProtoMessage()    {}
func (*RPCForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{14}
}

func (m *RPCForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCForwardParams.Unmarshal(m, b)
}
func (m *RPCForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCForwardParams.Marshal(b, m, deterministic)
}
func (m *RPCForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCForwardParams.Merge(m, src)
}
func (m *RPCForwardParams) XXX_Size() int {
	return xxx_messageInfo_RPCForwardParams.Size(m)
}
func (m *RPCForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_RPCForwardParams proto.InternalMessageInfo

func (m *RPCForwardParams) GetViewID() uint32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *RPCForwardParams) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *RPCForwardParams) GetParameters() []*NGAny {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type NGVector3 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NGVector3) Reset()         { *m = NGVector3{} }
func (m *NGVector3) String() string { return proto.CompactTextString(m) }
func (*NGVector3) ProtoMessage()    {}
func (*NGVector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{15}
}

func (m *NGVector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NGVector3.Unmarshal(m, b)
}
func (m *NGVector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NGVector3.Marshal(b, m, deterministic)
}
func (m *NGVector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NGVector3.Merge(m, src)
}
func (m *NGVector3) XXX_Size() int {
	return xxx_messageInfo_NGVector3.Size(m)
}
func (m *NGVector3) XXX_DiscardUnknown() {
	xxx_messageInfo_NGVector3.DiscardUnknown(m)
}

var xxx_messageInfo_NGVector3 proto.InternalMessageInfo

func (m *NGVector3) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *NGVector3) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *NGVector3) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type NGQuaternion struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W                    float32  `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NGQuaternion) Reset()         { *m = NGQuaternion{} }
func (m *NGQuaternion) String() string { return proto.CompactTextString(m) }
func (*NGQuaternion) ProtoMessage()    {}
func (*NGQuaternion) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{16}
}

func (m *NGQuaternion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NGQuaternion.Unmarshal(m, b)
}
func (m *NGQuaternion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NGQuaternion.Marshal(b, m, deterministic)
}
func (m *NGQuaternion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NGQuaternion.Merge(m, src)
}
func (m *NGQuaternion) XXX_Size() int {
	return xxx_messageInfo_NGQuaternion.Size(m)
}
func (m *NGQuaternion) XXX_DiscardUnknown() {
	xxx_messageInfo_NGQuaternion.DiscardUnknown(m)
}

var xxx_messageInfo_NGQuaternion proto.InternalMessageInfo

func (m *NGQuaternion) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *NGQuaternion) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *NGQuaternion) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *NGQuaternion) GetW() float32 {
	if m != nil {
		return m.W
	}
	return 0
}

type NGColor struct {
	R                    float32  `protobuf:"fixed32,1,opt,name=r,proto3" json:"r,omitempty"`
	G                    float32  `protobuf:"fixed32,2,opt,name=g,proto3" json:"g,omitempty"`
	B                    float32  `protobuf:"fixed32,3,opt,name=b,proto3" json:"b,omitempty"`
	A                    float32  `protobuf:"fixed32,4,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NGColor) Reset()         { *m = NGColor{} }
func (m *NGColor) String() string { return proto.CompactTextString(m) }
func (*NGColor) ProtoMessage()    {}
func (*NGColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{17}
}

func (m *NGColor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NGColor.Unmarshal(m, b)
}
func (m *NGColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NGColor.Marshal(b, m, deterministic)
}
func (m *NGColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NGColor.Merge(m, src)
}
func (m *NGColor) XXX_Size() int {
	return xxx_messageInfo_NGColor.Size(m)
}
func (m *NGColor) XXX_DiscardUnknown() {
	xxx_messageInfo_NGColor.DiscardUnknown(m)
}

var xxx_messageInfo_NGColor proto.InternalMessageInfo

func (m *NGColor) GetR() float32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *NGColor) GetG() float32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *NGColor) GetB() float32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *NGColor) GetA() float32 {
	if m != nil {
		return m.A
	}
	return 0
}

//LaunchEventParams and LaunchEventForwardParams all use this message body
type InstantiationParams struct {
	Options              *CommonOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	PrefabName           string         `protobuf:"bytes,2,opt,name=prefabName,proto3" json:"prefabName,omitempty"`
	Position             *NGVector3     `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *NGQuaternion  `protobuf:"bytes,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	ViewIDs              []uint32       `protobuf:"varint,5,rep,packed,name=viewIDs,proto3" json:"viewIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InstantiationParams) Reset()         { *m = InstantiationParams{} }
func (m *InstantiationParams) String() string { return proto.CompactTextString(m) }
func (*InstantiationParams) ProtoMessage()    {}
func (*InstantiationParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{18}
}

func (m *InstantiationParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstantiationParams.Unmarshal(m, b)
}
func (m *InstantiationParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstantiationParams.Marshal(b, m, deterministic)
}
func (m *InstantiationParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstantiationParams.Merge(m, src)
}
func (m *InstantiationParams) XXX_Size() int {
	return xxx_messageInfo_InstantiationParams.Size(m)
}
func (m *InstantiationParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InstantiationParams.DiscardUnknown(m)
}

var xxx_messageInfo_InstantiationParams proto.InternalMessageInfo

func (m *InstantiationParams) GetOptions() *CommonOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *InstantiationParams) GetPrefabName() string {
	if m != nil {
		return m.PrefabName
	}
	return ""
}

func (m *InstantiationParams) GetPosition() *NGVector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *InstantiationParams) GetRotation() *NGQuaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *InstantiationParams) GetViewIDs() []uint32 {
	if m != nil {
		return m.ViewIDs
	}
	return nil
}

type InstantiationForwardParams struct {
	PrefabName           string        `protobuf:"bytes,1,opt,name=prefabName,proto3" json:"prefabName,omitempty"`
	Position             *NGVector3    `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *NGQuaternion `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	ViewIDs              []uint32      `protobuf:"varint,4,rep,packed,name=viewIDs,proto3" json:"viewIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InstantiationForwardParams) Reset()         { *m = InstantiationForwardParams{} }
func (m *InstantiationForwardParams) String() string { return proto.CompactTextString(m) }
func (*InstantiationForwardParams) ProtoMessage()    {}
func (*InstantiationForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{19}
}

func (m *InstantiationForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstantiationForwardParams.Unmarshal(m, b)
}
func (m *InstantiationForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstantiationForwardParams.Marshal(b, m, deterministic)
}
func (m *InstantiationForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstantiationForwardParams.Merge(m, src)
}
func (m *InstantiationForwardParams) XXX_Size() int {
	return xxx_messageInfo_InstantiationForwardParams.Size(m)
}
func (m *InstantiationForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InstantiationForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_InstantiationForwardParams proto.InternalMessageInfo

func (m *InstantiationForwardParams) GetPrefabName() string {
	if m != nil {
		return m.PrefabName
	}
	return ""
}

func (m *InstantiationForwardParams) GetPosition() *NGVector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *InstantiationForwardParams) GetRotation() *NGQuaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *InstantiationForwardParams) GetViewIDs() []uint32 {
	if m != nil {
		return m.ViewIDs
	}
	return nil
}

//LaunchEventParams and LaunchEventForwardParams all use this message body
type ViewSyncDataParams struct {
	ViewID               uint32   `protobuf:"varint,1,opt,name=viewID,proto3" json:"viewID,omitempty"`
	ViewSyncData         []*NGAny `protobuf:"bytes,2,rep,name=viewSyncData,proto3" json:"viewSyncData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewSyncDataParams) Reset()         { *m = ViewSyncDataParams{} }
func (m *ViewSyncDataParams) String() string { return proto.CompactTextString(m) }
func (*ViewSyncDataParams) ProtoMessage()    {}
func (*ViewSyncDataParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{20}
}

func (m *ViewSyncDataParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSyncDataParams.Unmarshal(m, b)
}
func (m *ViewSyncDataParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSyncDataParams.Marshal(b, m, deterministic)
}
func (m *ViewSyncDataParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSyncDataParams.Merge(m, src)
}
func (m *ViewSyncDataParams) XXX_Size() int {
	return xxx_messageInfo_ViewSyncDataParams.Size(m)
}
func (m *ViewSyncDataParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSyncDataParams.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSyncDataParams proto.InternalMessageInfo

func (m *ViewSyncDataParams) GetViewID() uint32 {
	if m != nil {
		return m.ViewID
	}
	return 0
}

func (m *ViewSyncDataParams) GetViewSyncData() []*NGAny {
	if m != nil {
		return m.ViewSyncData
	}
	return nil
}

type ViewSyncParams struct {
	Options              *CommonOptions        `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	VsdParams            []*ViewSyncDataParams `protobuf:"bytes,2,rep,name=vsdParams,proto3" json:"vsdParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ViewSyncParams) Reset()         { *m = ViewSyncParams{} }
func (m *ViewSyncParams) String() string { return proto.CompactTextString(m) }
func (*ViewSyncParams) ProtoMessage()    {}
func (*ViewSyncParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{21}
}

func (m *ViewSyncParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSyncParams.Unmarshal(m, b)
}
func (m *ViewSyncParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSyncParams.Marshal(b, m, deterministic)
}
func (m *ViewSyncParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSyncParams.Merge(m, src)
}
func (m *ViewSyncParams) XXX_Size() int {
	return xxx_messageInfo_ViewSyncParams.Size(m)
}
func (m *ViewSyncParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSyncParams.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSyncParams proto.InternalMessageInfo

func (m *ViewSyncParams) GetOptions() *CommonOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ViewSyncParams) GetVsdParams() []*ViewSyncDataParams {
	if m != nil {
		return m.VsdParams
	}
	return nil
}

type ViewSyncForwardParams struct {
	VsdParams            []*ViewSyncDataParams `protobuf:"bytes,1,rep,name=vsdParams,proto3" json:"vsdParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ViewSyncForwardParams) Reset()         { *m = ViewSyncForwardParams{} }
func (m *ViewSyncForwardParams) String() string { return proto.CompactTextString(m) }
func (*ViewSyncForwardParams) ProtoMessage()    {}
func (*ViewSyncForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{22}
}

func (m *ViewSyncForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSyncForwardParams.Unmarshal(m, b)
}
func (m *ViewSyncForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSyncForwardParams.Marshal(b, m, deterministic)
}
func (m *ViewSyncForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSyncForwardParams.Merge(m, src)
}
func (m *ViewSyncForwardParams) XXX_Size() int {
	return xxx_messageInfo_ViewSyncForwardParams.Size(m)
}
func (m *ViewSyncForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSyncForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSyncForwardParams proto.InternalMessageInfo

func (m *ViewSyncForwardParams) GetVsdParams() []*ViewSyncDataParams {
	if m != nil {
		return m.VsdParams
	}
	return nil
}

type CustomEventParams struct {
	Options              *CommonOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	EventID              uint32         `protobuf:"varint,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
	TargetPeerIds        []uint32       `protobuf:"varint,3,rep,packed,name=targetPeerIds,proto3" json:"targetPeerIds,omitempty"`
	CustomData           []*NGAny       `protobuf:"bytes,4,rep,name=customData,proto3" json:"customData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CustomEventParams) Reset()         { *m = CustomEventParams{} }
func (m *CustomEventParams) String() string { return proto.CompactTextString(m) }
func (*CustomEventParams) ProtoMessage()    {}
func (*CustomEventParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{23}
}

func (m *CustomEventParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomEventParams.Unmarshal(m, b)
}
func (m *CustomEventParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomEventParams.Marshal(b, m, deterministic)
}
func (m *CustomEventParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomEventParams.Merge(m, src)
}
func (m *CustomEventParams) XXX_Size() int {
	return xxx_messageInfo_CustomEventParams.Size(m)
}
func (m *CustomEventParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomEventParams.DiscardUnknown(m)
}

var xxx_messageInfo_CustomEventParams proto.InternalMessageInfo

func (m *CustomEventParams) GetOptions() *CommonOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *CustomEventParams) GetEventID() uint32 {
	if m != nil {
		return m.EventID
	}
	return 0
}

func (m *CustomEventParams) GetTargetPeerIds() []uint32 {
	if m != nil {
		return m.TargetPeerIds
	}
	return nil
}

func (m *CustomEventParams) GetCustomData() []*NGAny {
	if m != nil {
		return m.CustomData
	}
	return nil
}

//Launch Event only has Forward params
type CustomEventForwardParams struct {
	EventID              uint32   `protobuf:"varint,1,opt,name=eventID,proto3" json:"eventID,omitempty"`
	CustomData           []*NGAny `protobuf:"bytes,2,rep,name=customData,proto3" json:"customData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomEventForwardParams) Reset()         { *m = CustomEventForwardParams{} }
func (m *CustomEventForwardParams) String() string { return proto.CompactTextString(m) }
func (*CustomEventForwardParams) ProtoMessage()    {}
func (*CustomEventForwardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{24}
}

func (m *CustomEventForwardParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomEventForwardParams.Unmarshal(m, b)
}
func (m *CustomEventForwardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomEventForwardParams.Marshal(b, m, deterministic)
}
func (m *CustomEventForwardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomEventForwardParams.Merge(m, src)
}
func (m *CustomEventForwardParams) XXX_Size() int {
	return xxx_messageInfo_CustomEventForwardParams.Size(m)
}
func (m *CustomEventForwardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomEventForwardParams.DiscardUnknown(m)
}

var xxx_messageInfo_CustomEventForwardParams proto.InternalMessageInfo

func (m *CustomEventForwardParams) GetEventID() uint32 {
	if m != nil {
		return m.EventID
	}
	return 0
}

func (m *CustomEventForwardParams) GetCustomData() []*NGAny {
	if m != nil {
		return m.CustomData
	}
	return nil
}

type SubscribeMsgChannelsParams struct {
	Channelids           []uint32 `protobuf:"varint,1,rep,packed,name=channelids,proto3" json:"channelids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeMsgChannelsParams) Reset()         { *m = SubscribeMsgChannelsParams{} }
func (m *SubscribeMsgChannelsParams) String() string { return proto.CompactTextString(m) }
func (*SubscribeMsgChannelsParams) ProtoMessage()    {}
func (*SubscribeMsgChannelsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{25}
}

func (m *SubscribeMsgChannelsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeMsgChannelsParams.Unmarshal(m, b)
}
func (m *SubscribeMsgChannelsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeMsgChannelsParams.Marshal(b, m, deterministic)
}
func (m *SubscribeMsgChannelsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeMsgChannelsParams.Merge(m, src)
}
func (m *SubscribeMsgChannelsParams) XXX_Size() int {
	return xxx_messageInfo_SubscribeMsgChannelsParams.Size(m)
}
func (m *SubscribeMsgChannelsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeMsgChannelsParams.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeMsgChannelsParams proto.InternalMessageInfo

func (m *SubscribeMsgChannelsParams) GetChannelids() []uint32 {
	if m != nil {
		return m.Channelids
	}
	return nil
}

type UnSubscribeMsgChannelsParams struct {
	Channelids           []uint32 `protobuf:"varint,1,rep,packed,name=channelids,proto3" json:"channelids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnSubscribeMsgChannelsParams) Reset()         { *m = UnSubscribeMsgChannelsParams{} }
func (m *UnSubscribeMsgChannelsParams) String() string { return proto.CompactTextString(m) }
func (*UnSubscribeMsgChannelsParams) ProtoMessage()    {}
func (*UnSubscribeMsgChannelsParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{26}
}

func (m *UnSubscribeMsgChannelsParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnSubscribeMsgChannelsParams.Unmarshal(m, b)
}
func (m *UnSubscribeMsgChannelsParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnSubscribeMsgChannelsParams.Marshal(b, m, deterministic)
}
func (m *UnSubscribeMsgChannelsParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnSubscribeMsgChannelsParams.Merge(m, src)
}
func (m *UnSubscribeMsgChannelsParams) XXX_Size() int {
	return xxx_messageInfo_UnSubscribeMsgChannelsParams.Size(m)
}
func (m *UnSubscribeMsgChannelsParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UnSubscribeMsgChannelsParams.DiscardUnknown(m)
}

var xxx_messageInfo_UnSubscribeMsgChannelsParams proto.InternalMessageInfo

func (m *UnSubscribeMsgChannelsParams) GetChannelids() []uint32 {
	if m != nil {
		return m.Channelids
	}
	return nil
}

//send from client to server
type SendMessage struct {
	MsgType              MessageType                   `protobuf:"varint,1,opt,name=msgType,proto3,enum=server.MessageType" json:"msgType,omitempty"`
	CrParams             *CreateRoomParams             `protobuf:"bytes,2,opt,name=crParams,proto3" json:"crParams,omitempty"`
	JrParams             *JoinRoomParams               `protobuf:"bytes,3,opt,name=jrParams,proto3" json:"jrParams,omitempty"`
	JocrParams           *JoinOrCreateRoomParams       `protobuf:"bytes,4,opt,name=jocrParams,proto3" json:"jocrParams,omitempty"`
	LrParams             *LeaveRoomParams              `protobuf:"bytes,5,opt,name=lrParams,proto3" json:"lrParams,omitempty"`
	RpcParams            *RPCParams                    `protobuf:"bytes,6,opt,name=rpcParams,proto3" json:"rpcParams,omitempty"`
	IParams              *InstantiationParams          `protobuf:"bytes,7,opt,name=iParams,proto3" json:"iParams,omitempty"`
	VsParams             *ViewSyncParams               `protobuf:"bytes,8,opt,name=vsParams,proto3" json:"vsParams,omitempty"`
	CeParams             *CustomEventParams            `protobuf:"bytes,9,opt,name=ceParams,proto3" json:"ceParams,omitempty"`
	SmcParams            *SubscribeMsgChannelsParams   `protobuf:"bytes,10,opt,name=smcParams,proto3" json:"smcParams,omitempty"`
	UsmcParams           *UnSubscribeMsgChannelsParams `protobuf:"bytes,11,opt,name=usmcParams,proto3" json:"usmcParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SendMessage) Reset()         { *m = SendMessage{} }
func (m *SendMessage) String() string { return proto.CompactTextString(m) }
func (*SendMessage) ProtoMessage()    {}
func (*SendMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{27}
}

func (m *SendMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessage.Unmarshal(m, b)
}
func (m *SendMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessage.Marshal(b, m, deterministic)
}
func (m *SendMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessage.Merge(m, src)
}
func (m *SendMessage) XXX_Size() int {
	return xxx_messageInfo_SendMessage.Size(m)
}
func (m *SendMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessage proto.InternalMessageInfo

func (m *SendMessage) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_JoinLobby
}

func (m *SendMessage) GetCrParams() *CreateRoomParams {
	if m != nil {
		return m.CrParams
	}
	return nil
}

func (m *SendMessage) GetJrParams() *JoinRoomParams {
	if m != nil {
		return m.JrParams
	}
	return nil
}

func (m *SendMessage) GetJocrParams() *JoinOrCreateRoomParams {
	if m != nil {
		return m.JocrParams
	}
	return nil
}

func (m *SendMessage) GetLrParams() *LeaveRoomParams {
	if m != nil {
		return m.LrParams
	}
	return nil
}

func (m *SendMessage) GetRpcParams() *RPCParams {
	if m != nil {
		return m.RpcParams
	}
	return nil
}

func (m *SendMessage) GetIParams() *InstantiationParams {
	if m != nil {
		return m.IParams
	}
	return nil
}

func (m *SendMessage) GetVsParams() *ViewSyncParams {
	if m != nil {
		return m.VsParams
	}
	return nil
}

func (m *SendMessage) GetCeParams() *CustomEventParams {
	if m != nil {
		return m.CeParams
	}
	return nil
}

func (m *SendMessage) GetSmcParams() *SubscribeMsgChannelsParams {
	if m != nil {
		return m.SmcParams
	}
	return nil
}

func (m *SendMessage) GetUsmcParams() *UnSubscribeMsgChannelsParams {
	if m != nil {
		return m.UsmcParams
	}
	return nil
}

type ResponseSocketStatusMessage struct {
	SStatus              SocketStatus `protobuf:"varint,1,opt,name=sStatus,proto3,enum=server.SocketStatus" json:"sStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResponseSocketStatusMessage) Reset()         { *m = ResponseSocketStatusMessage{} }
func (m *ResponseSocketStatusMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseSocketStatusMessage) ProtoMessage()    {}
func (*ResponseSocketStatusMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{28}
}

func (m *ResponseSocketStatusMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseSocketStatusMessage.Unmarshal(m, b)
}
func (m *ResponseSocketStatusMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseSocketStatusMessage.Marshal(b, m, deterministic)
}
func (m *ResponseSocketStatusMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseSocketStatusMessage.Merge(m, src)
}
func (m *ResponseSocketStatusMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseSocketStatusMessage.Size(m)
}
func (m *ResponseSocketStatusMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseSocketStatusMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseSocketStatusMessage proto.InternalMessageInfo

func (m *ResponseSocketStatusMessage) GetSStatus() SocketStatus {
	if m != nil {
		return m.SStatus
	}
	return SocketStatus_Disconnected
}

//send from server to client
type ResponseOperationMessage struct {
	MsgType              MessageType                     `protobuf:"varint,1,opt,name=msgType,proto3,enum=server.MessageType" json:"msgType,omitempty"`
	CrrParams            *CreateRoomResponseParams       `protobuf:"bytes,2,opt,name=crrParams,proto3" json:"crrParams,omitempty"`
	JrrParams            *JoinRoomResponseParams         `protobuf:"bytes,3,opt,name=jrrParams,proto3" json:"jrrParams,omitempty"`
	JocrrParams          *JoinOrCreateRoomResponseParams `protobuf:"bytes,4,opt,name=jocrrParams,proto3" json:"jocrrParams,omitempty"`
	LrrParams            *LeaveRoomResponseParams        `protobuf:"bytes,5,opt,name=lrrParams,proto3" json:"lrrParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ResponseOperationMessage) Reset()         { *m = ResponseOperationMessage{} }
func (m *ResponseOperationMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseOperationMessage) ProtoMessage()    {}
func (*ResponseOperationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{29}
}

func (m *ResponseOperationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseOperationMessage.Unmarshal(m, b)
}
func (m *ResponseOperationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseOperationMessage.Marshal(b, m, deterministic)
}
func (m *ResponseOperationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseOperationMessage.Merge(m, src)
}
func (m *ResponseOperationMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseOperationMessage.Size(m)
}
func (m *ResponseOperationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseOperationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseOperationMessage proto.InternalMessageInfo

func (m *ResponseOperationMessage) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_JoinLobby
}

func (m *ResponseOperationMessage) GetCrrParams() *CreateRoomResponseParams {
	if m != nil {
		return m.CrrParams
	}
	return nil
}

func (m *ResponseOperationMessage) GetJrrParams() *JoinRoomResponseParams {
	if m != nil {
		return m.JrrParams
	}
	return nil
}

func (m *ResponseOperationMessage) GetJocrrParams() *JoinOrCreateRoomResponseParams {
	if m != nil {
		return m.JocrrParams
	}
	return nil
}

func (m *ResponseOperationMessage) GetLrrParams() *LeaveRoomResponseParams {
	if m != nil {
		return m.LrrParams
	}
	return nil
}

//need to notifiy others in the room.
type ForwardMessage struct {
	MsgType              MessageType                    `protobuf:"varint,1,opt,name=msgType,proto3,enum=server.MessageType" json:"msgType,omitempty"`
	PeerId               uint32                         `protobuf:"varint,2,opt,name=peerId,proto3" json:"peerId,omitempty"`
	JrfParams            *JoinRoomForwardParams         `protobuf:"bytes,3,opt,name=jrfParams,proto3" json:"jrfParams,omitempty"`
	JocrfParams          *JoinOrCreateRoomForwardParams `protobuf:"bytes,4,opt,name=jocrfParams,proto3" json:"jocrfParams,omitempty"`
	LrfParams            *LeaveRoomForwardParams        `protobuf:"bytes,5,opt,name=lrfParams,proto3" json:"lrfParams,omitempty"`
	RfParams             *RPCForwardParams              `protobuf:"bytes,6,opt,name=rfParams,proto3" json:"rfParams,omitempty"`
	IfParams             *InstantiationForwardParams    `protobuf:"bytes,7,opt,name=ifParams,proto3" json:"ifParams,omitempty"`
	VsfParams            *ViewSyncForwardParams         `protobuf:"bytes,8,opt,name=vsfParams,proto3" json:"vsfParams,omitempty"`
	CeParams             *CustomEventForwardParams      `protobuf:"bytes,9,opt,name=ceParams,proto3" json:"ceParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ForwardMessage) Reset()         { *m = ForwardMessage{} }
func (m *ForwardMessage) String() string { return proto.CompactTextString(m) }
func (*ForwardMessage) ProtoMessage()    {}
func (*ForwardMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{30}
}

func (m *ForwardMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardMessage.Unmarshal(m, b)
}
func (m *ForwardMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardMessage.Marshal(b, m, deterministic)
}
func (m *ForwardMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardMessage.Merge(m, src)
}
func (m *ForwardMessage) XXX_Size() int {
	return xxx_messageInfo_ForwardMessage.Size(m)
}
func (m *ForwardMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardMessage proto.InternalMessageInfo

func (m *ForwardMessage) GetMsgType() MessageType {
	if m != nil {
		return m.MsgType
	}
	return MessageType_JoinLobby
}

func (m *ForwardMessage) GetPeerId() uint32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *ForwardMessage) GetJrfParams() *JoinRoomForwardParams {
	if m != nil {
		return m.JrfParams
	}
	return nil
}

func (m *ForwardMessage) GetJocrfParams() *JoinOrCreateRoomForwardParams {
	if m != nil {
		return m.JocrfParams
	}
	return nil
}

func (m *ForwardMessage) GetLrfParams() *LeaveRoomForwardParams {
	if m != nil {
		return m.LrfParams
	}
	return nil
}

func (m *ForwardMessage) GetRfParams() *RPCForwardParams {
	if m != nil {
		return m.RfParams
	}
	return nil
}

func (m *ForwardMessage) GetIfParams() *InstantiationForwardParams {
	if m != nil {
		return m.IfParams
	}
	return nil
}

func (m *ForwardMessage) GetVsfParams() *ViewSyncForwardParams {
	if m != nil {
		return m.VsfParams
	}
	return nil
}

func (m *ForwardMessage) GetCeParams() *CustomEventForwardParams {
	if m != nil {
		return m.CeParams
	}
	return nil
}

//send from server to client
type ReceiveMessage struct {
	ReceiveMsgType       ReceiveMessageType           `protobuf:"varint,1,opt,name=receiveMsgType,proto3,enum=server.ReceiveMessageType" json:"receiveMsgType,omitempty"`
	RssMsg               *ResponseSocketStatusMessage `protobuf:"bytes,2,opt,name=rssMsg,proto3" json:"rssMsg,omitempty"`
	RoMsg                *ResponseOperationMessage    `protobuf:"bytes,3,opt,name=roMsg,proto3" json:"roMsg,omitempty"`
	FMsg                 *ForwardMessage              `protobuf:"bytes,4,opt,name=fMsg,proto3" json:"fMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ReceiveMessage) Reset()         { *m = ReceiveMessage{} }
func (m *ReceiveMessage) String() string { return proto.CompactTextString(m) }
func (*ReceiveMessage) ProtoMessage()    {}
func (*ReceiveMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff7f458fcc31b586, []int{31}
}

func (m *ReceiveMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveMessage.Unmarshal(m, b)
}
func (m *ReceiveMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveMessage.Marshal(b, m, deterministic)
}
func (m *ReceiveMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveMessage.Merge(m, src)
}
func (m *ReceiveMessage) XXX_Size() int {
	return xxx_messageInfo_ReceiveMessage.Size(m)
}
func (m *ReceiveMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveMessage proto.InternalMessageInfo

func (m *ReceiveMessage) GetReceiveMsgType() ReceiveMessageType {
	if m != nil {
		return m.ReceiveMsgType
	}
	return ReceiveMessageType_ResponseSocketStatus
}

func (m *ReceiveMessage) GetRssMsg() *ResponseSocketStatusMessage {
	if m != nil {
		return m.RssMsg
	}
	return nil
}

func (m *ReceiveMessage) GetRoMsg() *ResponseOperationMessage {
	if m != nil {
		return m.RoMsg
	}
	return nil
}

func (m *ReceiveMessage) GetFMsg() *ForwardMessage {
	if m != nil {
		return m.FMsg
	}
	return nil
}

func init() {
	proto.RegisterEnum("server.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("server.CacheOptions", CacheOptions_name, CacheOptions_value)
	proto.RegisterEnum("server.RPCTarget", RPCTarget_name, RPCTarget_value)
	proto.RegisterEnum("server.SocketStatus", SocketStatus_name, SocketStatus_value)
	proto.RegisterEnum("server.ReceiveMessageType", ReceiveMessageType_name, ReceiveMessageType_value)
	proto.RegisterType((*NGAny)(nil), "server.NGAny")
	proto.RegisterType((*CommonOptions)(nil), "server.CommonOptions")
	proto.RegisterType((*CreateRoomParams)(nil), "server.CreateRoomParams")
	proto.RegisterType((*CreateRoomResponseParams)(nil), "server.CreateRoomResponseParams")
	proto.RegisterType((*JoinRoomParams)(nil), "server.JoinRoomParams")
	proto.RegisterType((*JoinRoomResponseParams)(nil), "server.JoinRoomResponseParams")
	proto.RegisterType((*JoinRoomForwardParams)(nil), "server.JoinRoomForwardParams")
	proto.RegisterType((*JoinOrCreateRoomParams)(nil), "server.JoinOrCreateRoomParams")
	proto.RegisterType((*JoinOrCreateRoomResponseParams)(nil), "server.JoinOrCreateRoomResponseParams")
	proto.RegisterType((*JoinOrCreateRoomForwardParams)(nil), "server.JoinOrCreateRoomForwardParams")
	proto.RegisterType((*LeaveRoomParams)(nil), "server.LeaveRoomParams")
	proto.RegisterType((*LeaveRoomResponseParams)(nil), "server.LeaveRoomResponseParams")
	proto.RegisterType((*LeaveRoomForwardParams)(nil), "server.LeaveRoomForwardParams")
	proto.RegisterType((*RPCParams)(nil), "server.RPCParams")
	proto.RegisterType((*RPCForwardParams)(nil), "server.RPCForwardParams")
	proto.RegisterType((*NGVector3)(nil), "server.NGVector3")
	proto.RegisterType((*NGQuaternion)(nil), "server.NGQuaternion")
	proto.RegisterType((*NGColor)(nil), "server.NGColor")
	proto.RegisterType((*InstantiationParams)(nil), "server.InstantiationParams")
	proto.RegisterType((*InstantiationForwardParams)(nil), "server.InstantiationForwardParams")
	proto.RegisterType((*ViewSyncDataParams)(nil), "server.ViewSyncDataParams")
	proto.RegisterType((*ViewSyncParams)(nil), "server.ViewSyncParams")
	proto.RegisterType((*ViewSyncForwardParams)(nil), "server.ViewSyncForwardParams")
	proto.RegisterType((*CustomEventParams)(nil), "server.CustomEventParams")
	proto.RegisterType((*CustomEventForwardParams)(nil), "server.CustomEventForwardParams")
	proto.RegisterType((*SubscribeMsgChannelsParams)(nil), "server.SubscribeMsgChannelsParams")
	proto.RegisterType((*UnSubscribeMsgChannelsParams)(nil), "server.UnSubscribeMsgChannelsParams")
	proto.RegisterType((*SendMessage)(nil), "server.SendMessage")
	proto.RegisterType((*ResponseSocketStatusMessage)(nil), "server.ResponseSocketStatusMessage")
	proto.RegisterType((*ResponseOperationMessage)(nil), "server.ResponseOperationMessage")
	proto.RegisterType((*ForwardMessage)(nil), "server.ForwardMessage")
	proto.RegisterType((*ReceiveMessage)(nil), "server.ReceiveMessage")
}

func init() { proto.RegisterFile("ng_message.proto", fileDescriptor_ff7f458fcc31b586) }

var fileDescriptor_ff7f458fcc31b586 = []byte{
	// 1764 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xdd, 0x72, 0xdb, 0xb8,
	0x15, 0x16, 0x24, 0x59, 0x3f, 0x47, 0x3f, 0xa6, 0x91, 0xd8, 0xc6, 0x7a, 0x37, 0x0e, 0xcb, 0x6e,
	0x3b, 0x5c, 0x77, 0x92, 0x74, 0x6d, 0x45, 0xb3, 0xd3, 0xa4, 0x99, 0x3a, 0x72, 0x1d, 0xbb, 0xb3,
	0x71, 0xbc, 0x50, 0x36, 0xb7, 0x3b, 0x94, 0x04, 0x2b, 0x4a, 0x25, 0x42, 0x03, 0x52, 0x72, 0xb4,
	0x7d, 0x85, 0xbe, 0x4d, 0x2f, 0xfa, 0x16, 0x9d, 0x3e, 0x42, 0xfb, 0x04, 0xbd, 0x6a, 0xaf, 0x3b,
	0x00, 0x09, 0x92, 0x90, 0xe5, 0x78, 0xe3, 0x76, 0x72, 0x67, 0x9c, 0xf3, 0x7d, 0xe7, 0x1c, 0x1c,
	0x7c, 0x38, 0x84, 0x05, 0x96, 0x3f, 0xfc, 0x61, 0xc2, 0x82, 0xc0, 0x1b, 0xb2, 0x87, 0x53, 0xc1,
	0x43, 0x8e, 0x4b, 0x01, 0x13, 0x73, 0x26, 0x9c, 0x7f, 0x15, 0x61, 0xed, 0xec, 0xc5, 0xa1, 0xbf,
	0xc0, 0x5f, 0x40, 0xc5, 0x1f, 0x1e, 0xf1, 0x59, 0x6f, 0xcc, 0x48, 0xcd, 0x46, 0x2e, 0x3a, 0xc9,
	0xd1, 0xc4, 0x82, 0x77, 0xa0, 0xec, 0x0f, 0x8f, 0xc7, 0xdc, 0x0b, 0x49, 0xdd, 0x46, 0x6e, 0xfe,
	0x24, 0x47, 0xb5, 0x21, 0xf2, 0x9d, 0xfa, 0xe1, 0xc1, 0x3e, 0x69, 0xd8, 0xc8, 0x5d, 0x8b, 0x7c,
	0xca, 0x90, 0xf8, 0xda, 0x2d, 0xd2, 0xb4, 0x91, 0x5b, 0x48, 0x7c, 0xed, 0x56, 0x94, 0xf1, 0xfb,
	0x91, 0x22, 0xae, 0xdb, 0xc8, 0x6d, 0x44, 0x19, 0x23, 0x4b, 0xea, 0x6d, 0xb7, 0x88, 0x65, 0x23,
	0xb7, 0x98, 0x7a, 0x35, 0xb7, 0x1b, 0x71, 0x37, 0x6c, 0xe4, 0x6e, 0x44, 0xde, 0x6e, 0x86, 0xdb,
	0x8d, 0xb8, 0xd8, 0x46, 0x2e, 0x4e, 0xbd, 0xed, 0x16, 0xde, 0x85, 0xaa, 0x3f, 0x3c, 0x1e, 0xbd,
	0x67, 0x83, 0x83, 0x7d, 0x72, 0xc7, 0x46, 0x6e, 0xf9, 0x24, 0x47, 0x53, 0x53, 0xc6, 0xdf, 0x6e,
	0x91, 0xbb, 0x36, 0x72, 0x4b, 0x19, 0x7f, 0xbb, 0x85, 0x6d, 0x00, 0x7f, 0xd8, 0xbd, 0x88, 0x03,
	0x6c, 0xda, 0xc8, 0x5d, 0x3f, 0xc9, 0xd1, 0x8c, 0x2d, 0x8b, 0x68, 0xb7, 0xc8, 0x96, 0x8d, 0x5c,
	0x2b, 0x8b, 0x68, 0xb7, 0x30, 0x81, 0x92, 0x3f, 0x7c, 0xce, 0xf9, 0x98, 0x6c, 0xdb, 0xc8, 0xad,
	0x9c, 0xe4, 0x68, 0xbc, 0x8e, 0x6b, 0x0f, 0xc5, 0xc8, 0x1f, 0x12, 0x62, 0x23, 0xb7, 0x1a, 0xd7,
	0xae, 0x2c, 0x51, 0x3f, 0x9f, 0x2f, 0x42, 0x16, 0x90, 0xcf, 0x6c, 0xe4, 0xd6, 0xa3, 0x7e, 0x2a,
	0x03, 0xfe, 0x5a, 0xd6, 0xfd, 0x86, 0xf5, 0x43, 0x2e, 0x0e, 0xc8, 0x7d, 0x1b, 0xb9, 0xb5, 0xfd,
	0x8d, 0x87, 0xd1, 0x39, 0x3f, 0x3c, 0x7b, 0x11, 0x3b, 0xa2, 0xad, 0xc4, 0x0b, 0xfc, 0x1b, 0xa8,
	0xfb, 0xc3, 0xef, 0x66, 0x5e, 0xc8, 0x84, 0x3f, 0xe2, 0x3e, 0xb1, 0x15, 0xeb, 0x6e, 0xca, 0x4a,
	0x7d, 0x27, 0x39, 0x6a, 0x60, 0xf1, 0xaf, 0x64, 0x29, 0x1d, 0x3e, 0xe6, 0x82, 0xfc, 0x4c, 0xd1,
	0xd6, 0x53, 0x9a, 0x32, 0x47, 0xb5, 0xa9, 0x3f, 0x9f, 0x57, 0xe4, 0x7e, 0x5f, 0x2f, 0xa6, 0xcc,
	0x99, 0x41, 0xa3, 0xc3, 0x27, 0x13, 0xee, 0xbf, 0x9a, 0x86, 0x23, 0xee, 0x07, 0x78, 0x0f, 0xac,
	0x80, 0xf9, 0x83, 0xd7, 0xbc, 0xf3, 0xd6, 0xf3, 0x7d, 0x36, 0x3e, 0x1d, 0x04, 0x04, 0xd9, 0x05,
	0xb7, 0x41, 0xaf, 0xd8, 0xf1, 0x37, 0x50, 0xef, 0x7b, 0xfd, 0xb7, 0x2c, 0xe6, 0x92, 0xbc, 0x8d,
	0xdc, 0x66, 0x5a, 0x6f, 0x27, 0xe3, 0xa3, 0x06, 0xd2, 0x39, 0x01, 0xab, 0x23, 0x98, 0x17, 0x32,
	0xca, 0xf9, 0xe4, 0xdc, 0x13, 0xde, 0x24, 0xc0, 0x5b, 0x50, 0x12, 0x9c, 0x4f, 0x4e, 0x07, 0x04,
	0xc9, 0x46, 0xd3, 0x78, 0x85, 0xbf, 0x80, 0xea, 0xc4, 0x7b, 0x7f, 0x36, 0x9b, 0xf4, 0x98, 0x50,
	0x29, 0x1a, 0x34, 0x35, 0x38, 0x3e, 0x90, 0x34, 0x12, 0x65, 0xc1, 0x94, 0xfb, 0x01, 0x8b, 0x23,
	0xda, 0x50, 0x13, 0x2c, 0x9c, 0x09, 0xff, 0x8d, 0x37, 0x9e, 0x31, 0x15, 0xb6, 0x41, 0xb3, 0x26,
	0x4c, 0xa0, 0x1c, 0xdf, 0x44, 0x15, 0xb9, 0x4a, 0xf5, 0x52, 0x56, 0x33, 0x65, 0x4c, 0x9c, 0x0e,
	0x48, 0x41, 0xd1, 0xe2, 0x95, 0xe3, 0x42, 0xf3, 0x0f, 0x7c, 0xe4, 0xdf, 0x5c, 0xb7, 0x33, 0x86,
	0x2d, 0x8d, 0xfc, 0x04, 0x75, 0x6d, 0xc3, 0xa6, 0xce, 0x76, 0xcc, 0xc5, 0xa5, 0x27, 0x06, 0x51,
	0x32, 0xe7, 0x2c, 0x2a, 0xe3, 0x95, 0xf8, 0x3f, 0x35, 0x3c, 0x84, 0xdd, 0xe5, 0x78, 0x9f, 0x60,
	0x7b, 0xf7, 0xe1, 0xde, 0x72, 0x56, 0x73, 0x9b, 0x5f, 0xc1, 0xfa, 0xb7, 0xcc, 0x9b, 0xff, 0x84,
	0xfd, 0x39, 0x13, 0xd8, 0x4e, 0xa0, 0x9f, 0xa0, 0x74, 0x02, 0x5b, 0x49, 0x3a, 0xb3, 0xe6, 0xbf,
	0x21, 0xa8, 0xd2, 0xf3, 0x4e, 0x9c, 0xfb, 0x11, 0x94, 0x79, 0x7c, 0x91, 0x90, 0xba, 0xc1, 0x9b,
	0xc9, 0x45, 0xca, 0xde, 0x50, 0xaa, 0x51, 0xf8, 0x2b, 0x28, 0x85, 0x9e, 0x18, 0xb2, 0x30, 0xbe,
	0x78, 0xc9, 0x78, 0xa1, 0xe7, 0x9d, 0xd7, 0xca, 0x41, 0x63, 0x80, 0xac, 0x6d, 0x3e, 0x62, 0x97,
	0xa7, 0x47, 0xba, 0xb6, 0x68, 0x85, 0x77, 0x01, 0x26, 0x2c, 0x7c, 0xcb, 0x07, 0x67, 0xde, 0x84,
	0x91, 0xa2, 0xda, 0x50, 0xc6, 0x82, 0x1f, 0x00, 0x4c, 0x65, 0x75, 0x2c, 0x64, 0x22, 0x20, 0x6b,
	0x76, 0xc1, 0xad, 0xed, 0x37, 0xd2, 0xc1, 0x72, 0xe8, 0x2f, 0x68, 0x06, 0xe0, 0x2c, 0xc0, 0xa2,
	0xe7, 0x1d, 0x63, 0x93, 0x99, 0xd4, 0xe8, 0x03, 0xa9, 0xf3, 0x37, 0xa4, 0x2e, 0xdc, 0x94, 0xfa,
	0x31, 0x54, 0x93, 0xa9, 0x8a, 0xeb, 0x80, 0xde, 0xab, 0x74, 0x79, 0x8a, 0xde, 0xcb, 0xd5, 0x42,
	0x25, 0xc8, 0x53, 0xb4, 0x90, 0xab, 0x1f, 0x55, 0x17, 0xf2, 0x14, 0xfd, 0xe8, 0x1c, 0x43, 0x3d,
	0x3b, 0x56, 0x7f, 0x3a, 0x53, 0xae, 0x2e, 0x55, 0xc7, 0xf2, 0x14, 0x5d, 0x3a, 0x87, 0x50, 0x8e,
	0xe7, 0xac, 0x74, 0x08, 0x1d, 0x42, 0xad, 0x86, 0x3a, 0xc4, 0x50, 0xae, 0x7a, 0x3a, 0x44, 0x4f,
	0xae, 0x3c, 0x1d, 0xc2, 0x73, 0xfe, 0x89, 0xe0, 0xce, 0xa9, 0x1f, 0x84, 0x9e, 0x1f, 0x8e, 0x3c,
	0x79, 0xc2, 0xb7, 0xd5, 0xc5, 0x2e, 0xc0, 0x54, 0xb0, 0x0b, 0xaf, 0x97, 0xed, 0x6c, 0x6a, 0xc1,
	0x0f, 0xa0, 0x32, 0xe5, 0xc1, 0x48, 0x82, 0x55, 0x2d, 0xab, 0x3e, 0x4c, 0x34, 0x81, 0xe0, 0x5f,
	0x43, 0x45, 0xf0, 0x50, 0x55, 0xa4, 0x8a, 0xbd, 0xe6, 0x8b, 0x44, 0x13, 0x94, 0xbc, 0x23, 0xd1,
	0x21, 0x47, 0x92, 0x69, 0x50, 0xbd, 0x74, 0xfe, 0x8a, 0x60, 0xc7, 0xd8, 0xa3, 0xa9, 0x15, 0xb3,
	0x72, 0xf4, 0xc1, 0xca, 0xf3, 0x1f, 0x57, 0x79, 0xe1, 0x63, 0x2b, 0x2f, 0x9a, 0x95, 0xff, 0x00,
	0xf8, 0xcd, 0x88, 0x5d, 0x76, 0x17, 0x7e, 0xff, 0xc8, 0x0b, 0xbd, 0x1b, 0xc4, 0xfd, 0x35, 0xd4,
	0xe7, 0x19, 0x34, 0xc9, 0xaf, 0x92, 0xaf, 0x01, 0x71, 0xfe, 0x04, 0x4d, 0x9d, 0xe0, 0xb6, 0x07,
	0xff, 0x0d, 0x54, 0xe7, 0x41, 0xdc, 0xcb, 0x38, 0xe5, 0x8e, 0xa6, 0x5c, 0x2d, 0x9e, 0xa6, 0x60,
	0xe7, 0x3b, 0xd8, 0xd4, 0x00, 0xf3, 0x44, 0x8c, 0x90, 0xe8, 0x63, 0x42, 0xfe, 0x05, 0xc1, 0x46,
	0x67, 0x16, 0x84, 0x7c, 0xf2, 0xfb, 0x39, 0xf3, 0xc3, 0xdb, 0xee, 0x89, 0x40, 0x99, 0x49, 0xfe,
	0xe9, 0x51, 0xfc, 0x29, 0xd2, 0x4b, 0xfc, 0x25, 0x34, 0xa2, 0xe9, 0x76, 0xae, 0xe6, 0x6c, 0x34,
	0x23, 0x1a, 0xd4, 0x34, 0xca, 0x31, 0xd2, 0x57, 0x55, 0xa8, 0x73, 0x28, 0xae, 0x1c, 0x23, 0x29,
	0xc0, 0xe9, 0x03, 0xc9, 0x14, 0x6d, 0xf6, 0x22, 0x53, 0x0a, 0x32, 0x4b, 0x31, 0x93, 0xe4, 0x6f,
	0x4a, 0xf2, 0x14, 0x76, 0xba, 0xb3, 0x5e, 0xd0, 0x17, 0xa3, 0x1e, 0x7b, 0x19, 0x0c, 0xe3, 0x17,
	0x55, 0x90, 0x5e, 0x82, 0x7e, 0x64, 0x19, 0x25, 0x6f, 0xaf, 0x8c, 0xc5, 0x79, 0x06, 0x5f, 0x7c,
	0xef, 0xff, 0x0f, 0xfc, 0xff, 0x14, 0xa1, 0xd6, 0x65, 0xfe, 0xe0, 0x65, 0xfc, 0xdd, 0x7a, 0x00,
	0xe5, 0x49, 0xa0, 0x5e, 0x83, 0x6a, 0x5b, 0xcd, 0xfd, 0x3b, 0xba, 0xf2, 0x18, 0x21, 0x5d, 0x54,
	0x63, 0x70, 0x0b, 0x2a, 0x7d, 0x91, 0x68, 0x4c, 0x1e, 0x21, 0x49, 0x8e, 0x70, 0xe9, 0x85, 0x41,
	0x13, 0x24, 0xde, 0x87, 0xca, 0x3b, 0xcd, 0x8a, 0xae, 0xe2, 0x96, 0x66, 0x99, 0xcf, 0x29, 0x9a,
	0xe0, 0xf0, 0x33, 0x80, 0x77, 0x3c, 0xc9, 0x15, 0x8d, 0x9e, 0xdd, 0x2c, 0xeb, 0xea, 0x9b, 0x86,
	0x66, 0x18, 0xf8, 0x00, 0x2a, 0x63, 0xcd, 0x5e, 0x53, 0xec, 0x6d, 0xcd, 0x5e, 0x7a, 0x2a, 0xd0,
	0x04, 0x88, 0x1f, 0x41, 0x55, 0x4c, 0xe3, 0x1b, 0x48, 0x4a, 0xe6, 0x8c, 0x49, 0xbe, 0xd5, 0x34,
	0xc5, 0xe0, 0xc7, 0x50, 0x1e, 0xc5, 0xf0, 0xb2, 0x82, 0x7f, 0xae, 0xe1, 0x2b, 0x86, 0x39, 0xd5,
	0x58, 0xd9, 0x90, 0x79, 0x7c, 0x62, 0xa4, 0x62, 0x36, 0xc4, 0x1c, 0x03, 0x34, 0xc1, 0xe1, 0xc7,
	0x50, 0xe9, 0xc7, 0x2f, 0x15, 0x52, 0x55, 0x9c, 0xcf, 0x92, 0xd6, 0x2f, 0xdf, 0x34, 0x9a, 0x40,
	0xf1, 0xef, 0xa0, 0x1a, 0x4c, 0xf4, 0x96, 0x40, 0xf1, 0x1c, 0xcd, 0xbb, 0x5e, 0x47, 0x34, 0x25,
	0xe1, 0x23, 0x80, 0x59, 0x1a, 0xa2, 0xa6, 0x42, 0x7c, 0xa9, 0x43, 0x7c, 0x48, 0x8c, 0x34, 0xc3,
	0x73, 0x5e, 0xc2, 0xe7, 0xfa, 0xb9, 0xd5, 0xe5, 0xfd, 0x3f, 0xb2, 0xb0, 0x1b, 0x7a, 0xe1, 0x2c,
	0xd0, 0x3a, 0x7c, 0x08, 0xe5, 0x20, 0xb2, 0xc4, 0x3a, 0x4c, 0x86, 0x75, 0x16, 0x4d, 0x35, 0xc8,
	0xf9, 0x7b, 0x1e, 0x88, 0x8e, 0xf7, 0x6a, 0xca, 0x84, 0x6a, 0xf3, 0x2d, 0x45, 0xfd, 0x0c, 0xaa,
	0x7d, 0x61, 0xaa, 0xda, 0xbe, 0xaa, 0x6a, 0xf3, 0xb1, 0x48, 0x53, 0x0a, 0x7e, 0x0a, 0xd5, 0x77,
	0xc2, 0xd4, 0xf7, 0xee, 0xb2, 0xbe, 0x97, 0xd9, 0x09, 0x01, 0x9f, 0x40, 0x4d, 0xca, 0xd6, 0x54,
	0xfa, 0x2f, 0xaf, 0x53, 0xfa, 0x52, 0x9c, 0x2c, 0x15, 0xff, 0x16, 0xaa, 0x63, 0x61, 0x6a, 0xfe,
	0xfe, 0x15, 0xcd, 0x2f, 0x17, 0x92, 0x30, 0x9c, 0x3f, 0x17, 0xa1, 0x19, 0xcf, 0xbc, 0x5b, 0x36,
	0x32, 0x7d, 0x04, 0xe7, 0xb3, 0x8f, 0x60, 0xfc, 0x44, 0x36, 0xe8, 0xc2, 0x68, 0xd0, 0xbd, 0xe5,
	0x06, 0x19, 0xd3, 0x96, 0xa6, 0x78, 0xfc, 0x22, 0xea, 0xcf, 0x85, 0xd1, 0x9f, 0x5f, 0x5c, 0xd7,
	0x1f, 0x33, 0x4c, 0x96, 0x29, 0x8f, 0x69, 0x9c, 0x84, 0x59, 0x33, 0x8f, 0x69, 0xf5, 0x1b, 0x9d,
	0xa6, 0x04, 0x39, 0xf9, 0x12, 0x72, 0xc9, 0x9c, 0x7c, 0xcb, 0xaf, 0x5e, 0x9a, 0x20, 0xf1, 0x33,
	0xa8, 0x8c, 0x2e, 0x8c, 0x01, 0xe1, 0xac, 0x1c, 0x10, 0x4b, 0x7c, 0xcd, 0x91, 0x9d, 0x9b, 0x07,
	0x17, 0xc6, 0xa4, 0xb8, 0xb7, 0x3c, 0x29, 0x96, 0x4a, 0x4e, 0xf0, 0xf8, 0xe9, 0x95, 0x89, 0x61,
	0xaf, 0x98, 0x18, 0x4b, 0xa9, 0x35, 0xc3, 0xf9, 0x37, 0x82, 0x26, 0x65, 0x7d, 0x36, 0x9a, 0x33,
	0x2d, 0x87, 0xe7, 0xd0, 0x14, 0xb1, 0xc5, 0x50, 0x45, 0xf2, 0x28, 0x30, 0xf1, 0x4a, 0x1c, 0x4b,
	0x0c, 0xfc, 0x04, 0x4a, 0x22, 0x08, 0x5e, 0x06, 0xc3, 0xf8, 0xa6, 0xfd, 0x3c, 0xe5, 0x5e, 0x3b,
	0x1d, 0x68, 0x4c, 0xc1, 0x6d, 0x58, 0x13, 0x5c, 0x72, 0x0b, 0xe6, 0x76, 0xae, 0x9b, 0x04, 0x34,
	0x82, 0xe3, 0x3d, 0x28, 0x5e, 0x48, 0x5a, 0xd1, 0x9c, 0xb5, 0xa6, 0xda, 0xa9, 0xc2, 0xec, 0xfd,
	0x03, 0x41, 0x2d, 0xb3, 0x01, 0xdc, 0x80, 0xaa, 0x14, 0xd9, 0xb7, 0xbc, 0xd7, 0x5b, 0x58, 0x39,
	0xdc, 0x04, 0x50, 0x62, 0x89, 0xd6, 0x48, 0xae, 0x53, 0xf5, 0x59, 0x79, 0x5c, 0x87, 0x8a, 0x96,
	0xb4, 0x55, 0xc0, 0x77, 0xc1, 0x5a, 0x56, 0xa8, 0x55, 0x94, 0x21, 0x13, 0xc1, 0x59, 0x6b, 0xb8,
	0x0c, 0x05, 0x7a, 0xde, 0xb1, 0x4a, 0x78, 0x03, 0x1a, 0x86, 0x2a, 0xac, 0xb2, 0x0c, 0xa7, 0xcf,
	0xd9, 0xaa, 0xe0, 0x75, 0xa8, 0x65, 0x4e, 0xce, 0xaa, 0x62, 0x02, 0x77, 0x57, 0xcd, 0x5f, 0x0b,
	0xf0, 0x0e, 0x6c, 0xad, 0x9e, 0xcd, 0x56, 0x6d, 0xef, 0x09, 0xd4, 0xb3, 0x3f, 0xcf, 0x60, 0x0c,
	0xcd, 0xc3, 0xc1, 0xe0, 0x35, 0x97, 0xf5, 0x28, 0x87, 0x95, 0xc3, 0xdb, 0x70, 0x87, 0xb2, 0x09,
	0x9f, 0xb3, 0x63, 0xc1, 0x27, 0xa9, 0x03, 0xed, 0xd9, 0xea, 0xdf, 0xd6, 0xe8, 0x5f, 0x4c, 0x59,
	0xfa, 0xe1, 0x78, 0x6c, 0xe5, 0x30, 0x40, 0xe9, 0x55, 0xf8, 0x96, 0x89, 0xc0, 0x42, 0x7b, 0x8f,
	0xa0, 0x9e, 0x3d, 0x44, 0x6c, 0x41, 0xfd, 0x68, 0x14, 0xf4, 0xb9, 0xef, 0xb3, 0x7e, 0xc8, 0x06,
	0x56, 0x4e, 0x36, 0xa0, 0x93, 0x2c, 0xd1, 0x1e, 0x05, 0x7c, 0x55, 0x39, 0x72, 0x6f, 0xab, 0x34,
	0x61, 0xe5, 0xf0, 0x26, 0x6c, 0x5c, 0x39, 0x71, 0x0b, 0xe1, 0x1a, 0x94, 0xe3, 0x13, 0xb5, 0xf2,
	0xbd, 0x92, 0xfa, 0x71, 0xf5, 0xe0, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xcd, 0xf4, 0x84,
	0x70, 0x15, 0x00, 0x00,
}
